export appLogoIcon from './icons/app_logo.png';
export backIcon from './icons/back.png';
export crossIcon from './icons/cross.png';
export profileIcon from './icons/profile.png';
export checkIcon from './icons/check.png';
export gearIcon from './icons/gear.png';
export cameraIcon from './icons/camera.png';
export homeIcon from './icons/home.png';
export bellIcon from './icons/bell.png';
